import type { ModelDef } from '../../schema/types';
import type { SQLArtifact, SQLCompileApi } from '../../compile';
import {
  buildCount,
  buildDelete,
  buildInsert,
  buildSelect,
  buildUpdate,
} from '../../ir/build';
import {
  compileCount,
  compileDelete,
  compileInsert,
  compileSelect,
  compileUpdate,
} from './compile-from-ir';
import { schema } from '../../schema';

// Postgres compile API — same shape as Mongo's, returns SQLArtifact.
// Both APIs go through the same IR; only the per-adapter compileFromIR layer
// differs. SQL adapters share most of this; MySQL / SQLite (Wave 3) plug in
// their own dialect + reuse the same compile orchestration.

function modelKeyFor(model: ModelDef<any>): string {
  for (const key of Object.keys(schema as any)) {
    if ((schema as any)[key] === model) return key;
  }
  return model.collection;
}

export function buildPostgresCompileApi(model: ModelDef<any>): SQLCompileApi {
  const mk = modelKeyFor(model);
  return {
    findFirst:  (args?: any) => compileSelect(buildSelect(mk, model, args, 'one'), model),
    findUnique: (args: any)  => compileSelect(buildSelect(mk, model, args, 'one'), model),
    findMany:   (args?: any) => compileSelect(buildSelect(mk, model, args, 'many'), model),

    count:      (args?: any) => compileCount(buildCount(mk, model, args), model),

    create:     (args: any) => {
      // Wave 2a: rows are passed verbatim to the SQL compiler. Defaults are
      // generated by the database in DDL (DEFAULT clauses); the wrapper layer
      // (Wave 2b) decides whether to pre-apply or let the DB.
      return compileInsert(buildInsert(mk, model, { rows: [args.data], returning: args }), model);
    },
    createMany: (args: any) => {
      const rows = args.data ?? [];
      return compileInsert(buildInsert(mk, model, {
        rows,
        skipDuplicates: !!args.skipDuplicates,
      }), model);
    },

    update:     (args: any) => compileUpdate(buildUpdate(mk, model, {
      where: args.where, data: args.data, many: false, returning: args,
    }), model),
    updateMany: (args: any) => compileUpdate(buildUpdate(mk, model, {
      where: args.where, data: args.data, many: true,
    }), model),
    upsert:     (args: any) => compileUpdate(buildUpdate(mk, model, {
      where: args.where, data: args.update, many: false,
      upsertCreate: args.create, returning: args,
    }), model),

    delete:     (args: any) => compileDelete(buildDelete(mk, model, {
      where: args.where, many: false, returning: args,
    }), model),
    deleteMany: (args?: any) => compileDelete(buildDelete(mk, model, {
      where: args?.where, many: true,
    }), model),
  };
}

// Type-level no-op to silence unused-import warning if a consumer doesn't use it.
export type _SQLArtifact = SQLArtifact;
