import { defineConfig } from 'vitepress';
import sidebar from './sidebar.json' with { type: 'json' };

// The sidebar is generated by ../../sync.mjs from the README's own
// "Deep-dive companions" tables and its `##` headings, so the navigation
// cannot drift from the markdown it describes. Run `npm run sync`.

export default defineConfig({
  title: 'forge-orm',
  description:
    'One Prisma-shaped query API across MongoDB, PostgreSQL, MySQL, SQLite, DuckDB and SQL Server. No codegen.',

  // A project site is served from /<repo>/, not the domain root.
  base: '/forge-orm/',
  cleanUrls: true,
  lastUpdated: true,

  // The reference pages are copied verbatim from docs/, which cross-link
  // by anchors that do not always exist. A missing anchor should not stop
  // a docs deploy.
  ignoreDeadLinks: true,

  head: [
    ['meta', { name: 'theme-color', content: '#c2410c' }],
    ['meta', { property: 'og:title', content: 'forge-orm' }],
    ['meta', {
      property: 'og:description',
      content: 'One Prisma-shaped query API. Six databases. No codegen.',
    }],
  ],

  themeConfig: {
    search: {
      // Local index — no Algolia account, no third party, works offline.
      provider: 'local',
      options: {
        detailedView: true,
      },
    },

    nav: [
      { text: 'Guide', link: '/guide/introduction', activeMatch: '/guide/' },
      { text: 'Reference', link: '/reference/model', activeMatch: '/reference/' },
      { text: 'Examples', link: '/examples' },
      { text: 'Changelog', link: '/changelog' },
      {
        text: 'npm',
        link: 'https://www.npmjs.com/package/forge-orm',
      },
    ],

    sidebar,

    socialLinks: [
      { icon: 'github', link: 'https://github.com/johnsonfash/forge-orm' },
      { icon: 'npm', link: 'https://www.npmjs.com/package/forge-orm' },
    ],

    editLink: {
      // Points at the SOURCE file, not the generated copy — the whole
      // point of keeping the markdown authoritative.
      pattern: ({ filePath }) => {
        const repo = 'https://github.com/johnsonfash/forge-orm/edit/main';
        if (filePath.startsWith('reference/')) {
          const name = filePath.replace('reference/', '').replace('.md', '').toUpperCase();
          return `${repo}/docs/${name}.md`;
        }
        if (filePath === 'changelog.md') return `${repo}/CHANGELOG.md`;
        if (filePath === 'examples.md') return `${repo}/examples/README.md`;
        return `${repo}/README.md`;
      },
      text: 'Edit the source markdown',
    },

    outline: { level: [2, 3], label: 'On this page' },

    docFooter: { prev: 'Previous', next: 'Next' },

    footer: {
      message:
        'MIT licensed. Built from the repository\'s own markdown — README.md, CHANGELOG.md and docs/.',
      copyright: '© johnsonfash',
    },
  },
});
